### PR TITLE
Review/modex consortium

### PR DESCRIPTION
**Pull request by chrwm**
Closes https://github.com/OpenEnergyPlatform/data-preprocessing/issues/88

Cheery-picked grouped open_MODEX sources from https://github.com/OpenEnergyPlatform/data-preprocessing/pull/73

Should have been added the this PR https://github.com/OpenEnergyPlatform/data-preprocessing/pull/87

### CODE REVIEW

**Review by jh-RLI — COMMENTED** [review]
I´m not sure if it is good practice to publish actual data (CSV files) on GitHub. IMO the current workflow suggests uploading the data to the table on the OEP (I thought the consortium tables will be empty?). Or is there any reason to include the csv files I´m not aware of? @chrwm 

Files:
oed_scalar_publish.csv
open_MODEX_base_check.csv

**Comment by jh-RLI** [comment]
OH just noticed that GitHub showed these files to me, but they actually don't exist in the folder ?! I'm experiencing some issues with GitHub in the previous days. @chrwm can you check if the files still exists? Otherwise, I approve this PR.

**Review by jh-RLI — APPROVED** [review]
LGTM :)

**Comment by chrwm** [comment]
Hi @jh-RLI, thanks for the review. The csv files should not be part of the pull request, I deleted them (which is part of the PR). 
The only thing missing in the metadata strings is the `id` field. I'll create the empty tables in the [Schema](https://openenergy-platform.org/dataedit/schemas): reference then and insert the id's to complete the process.

**Comment by chrwm** [comment]
Alright, I created all tables in model_draft and attached the correct metadata (incl. `id`). If @jh-RLI don't have more issue, I'll merge the pull request tomorrow and someone with rights can move the tables from model_draft to the reference schema.

**Comment by Ludee** [comment]
The PR created the files in the wrong folder containing a space.
I fixed it but added it to #71.
Tables are moved now!

**Pull request merged**
